# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic

TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv8-a
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic

TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)

#TARGET_BOARD_SUFFIX := _64
TARGET_USES_64_BIT_BINDER := true
#TARGET_SUPPORTS_64_BIT_APPS := true

# Board name
TARGET_BOOTLOADER_BOARD_NAME := ums312_2h10
TARGET_BOARD_PLATFORM := ums312_2h10
TARGET_NO_BOOTLOADER := true

TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64
# Prebuilt 2plus kernel
TARGET_PREBUILT_KERNEL := device/retroid/pocket2plus/prebuilt/kernel
# Prebuilt 2plus dtbo
BOARD_PREBUILT_DTBOIMAGE := device/retroid/pocket2plus/prebuilt/dtbo.img
# Include the prebuilt recovery dtbo
BOARD_INCLUDE_RECOVERY_DTBO := true

# Partitions
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true
BOARD_BOOTIMAGE_PARTITION_SIZE := 36700160
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 41943040
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 3670016000
BOARD_VENDORIMAGE_PARTITION_SIZE := 2097152000
BOARD_CACHEIMAGE_PARTITION_SIZE := 283115520
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 83886080
BOARD_DTBIMG_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_VENDOR := vendor

# Kernel and recoveryimage generation
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_MKBOOTIMG_ARGS += --base 0x00000000
BOARD_MKBOOTIMG_ARGS += --cmdline "console=ttyS1,115200n8 androidboot.selinux=permissive"
BOARD_MKBOOTIMG_ARGS += --pagesize 2048
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset 0x05400000
BOARD_MKBOOTIMG_ARGS += --tags_offset 0x00000100
BOARD_MKBOOTIMG_ARGS += --kernel_offset 0x00008000
BOARD_MKBOOTIMG_ARGS += --second_offset 0x00f00000
BOARD_MKBOOTIMG_ARGS += --header_version 1

# System prop
TARGET_SYSTEM_PROP += device/retroid/pocket2plus/system.prop

# Brightness
TW_BRIGHTNESS_PATH := /sys/class/backlight/sprd_backlight/brightness

# Recovery fstab
TARGET_RECOVERY_FSTAB := device/retroid/pocket2plus/recovery/recovery.fstab
BOARD_SUPPRESS_EMMC_WIPE := true

# Graphics
TARGET_RECOVERY_PIXEL_FORMAT := "RGBX_8888"

# Themes
DEVICE_RESOLUTION := 640x480
TARGET_SCREEN_HEIGHT := 480
TARGET_SCREEN_WIDTH := 640

# MTP
TW_HAS_MTP := true
TW_EXCLUDE_MTP := false
TW_MTP_DEVICE := /dev/mtp_usb
TARGET_USE_CUSTOM_LUN_FILE_PATH := /config/usb_gadget/g1/functions/mass_storage.gs6/lun.%d/file
RECOVERY_VARIANT := twrp
TW_USE_TOOLBOX := true
TW_EXCLUDE_TWRPAPP := true

# Logcat (for debugging)
TWRP_INCLUDE_LOGCAT := true
TARGET_USES_LOGD := true

# Use MKE2FS
TARGET_USES_MKE2FS := true

#BOARD_BUILD_SYSTEM_ROOT_IMAGE := true
BOARD_VNDK_VERSION := current

# CPU Temp
TW_CUSTOM_CPU_TEMP_PATH := /sys/devices/virtual/thermal/thermal_zone1/temp

